/* Experimental opt-in immutable cache; original generated bytes remain untouched. */
#include <pthread.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <unistd.h>
#include "aoe_relocate.h"
#define AOE_CACHE_COUNT 262144u
#define AOE_CACHE_TABLE (AOE_CACHE_COUNT*2)
struct aoe_cache_entry { struct aoe_fragment_key key; uint64_t hash; uint32_t slot; };
static pthread_mutex_t aoe_cache_lock=PTHREAD_MUTEX_INITIALIZER;
static struct aoe_cache_entry *aoe_cache_entries;
static BYTE *aoe_cache_code;
static unsigned aoe_cache_used;
static int aoe_cache_enabled,aoe_cache_attempted;
static pthread_once_t aoe_cache_enable_once=PTHREAD_ONCE_INIT;
static void aoe_cache_check_enabled(void)
{
 const char *name,*slash;
 if(!getenv("AOELAB_CODE_CACHE_GAME")||main_argc<1)return;
 /* Wine removes the loader argument before Windows code runs. */
 name=main_argv[0];
 if((slash=strrchr(name,'/')))name=slash+1;
 if((slash=strrchr(name,'\\')))name=slash+1;
 aoe_cache_enabled=!strcasecmp(name,"RelicCardinal.exe") ||
   (getenv("AOELAB_CODE_CACHE_TEST_RING")&&!strcasecmp(name,"test_runtime_cache.exe"));
}
static uint64_t aoe_cache_local_stats[16],*aoe_cache_stats=aoe_cache_local_stats;
static __thread uint64_t aoe_cache_thread_original,aoe_cache_thread_shadow;
static __thread unsigned aoe_cache_thread_len;
static void aoe_cache_count(unsigned n){__atomic_fetch_add(&__atomic_load_n(&aoe_cache_stats,__ATOMIC_RELAXED)[n],1,__ATOMIC_RELAXED);}
static uint64_t aoe_cache_logical_pc(uint64_t pc)
{
 if(aoe_cache_thread_shadow && pc>=aoe_cache_thread_shadow && pc<aoe_cache_thread_shadow+aoe_cache_thread_len){aoe_cache_count(7);return aoe_cache_thread_original+(pc-aoe_cache_thread_shadow);}return pc;
}
static void aoe_cache_init(void)
{
 SIZE_T size=AOE_CACHE_COUNT*64;void *addr=(void*)0x190000000ULL;const char *directory=getenv("AOELAB_COUNTERS_DIR");
 aoe_cache_attempted=1;
 if(NtAllocateVirtualMemory(GetCurrentProcess(),&addr,0,&size,MEM_RESERVE|MEM_COMMIT,PAGE_EXECUTE_READWRITE))return;
 aoe_cache_entries=calloc(AOE_CACHE_TABLE,sizeof(*aoe_cache_entries));if(!aoe_cache_entries){size=0;NtFreeVirtualMemory(GetCurrentProcess(),&addr,&size,MEM_RELEASE);return;}aoe_cache_code=addr;
 if(directory&&directory[0]=='/'){
  char path[1024];int fd;void *map;
  if(snprintf(path,sizeof(path),"%s/codecache-%u.bin",directory,(unsigned)getpid())<(int)sizeof(path) && (fd=open(path,O_RDWR|O_CREAT|O_EXCL|O_NOFOLLOW,0600))>=0){
   if(!ftruncate(fd,4096)&&(map=mmap(NULL,4096,PROT_READ|PROT_WRITE,MAP_SHARED,fd,0))!=MAP_FAILED){uint64_t *p=map;p[0]=0x414f454341434831ULL;p[1]=1;p[2]=getpid();p[3]=16;__atomic_store_n(&aoe_cache_stats,p+4,__ATOMIC_RELAXED);}close(fd);
  }
 }
}
static uint64_t aoe_cache_target(uint64_t pc)
{
 uint64_t ring=0,hash=1469598103934665603ULL,result=pc;BYTE original[32],emitted[40];struct aoe_fragment_key key;unsigned available,i,index;const char *test;
 pthread_once(&aoe_cache_enable_once,aoe_cache_check_enabled);
 if(!aoe_cache_enabled || pc<0x140000000ULL || pc>=0x180000000ULL)return pc;
 test=getenv("AOELAB_CODE_CACHE_TEST_RING");
 if(test)ring=strtoull(test,NULL,0);
 else if(virtual_uninterrupted_read_memory((void*)0x147af7ad0ULL,&ring,sizeof(ring))!=sizeof(ring))return pc;
 if(!ring||pc<ring||pc>=ring+0x1000000)return pc;
 available=32-(pc-ring)%32;
 if(virtual_uninterrupted_read_memory((void*)pc,original,available)!=available)return pc;
 if(!aoe_fragment_key(original,available,pc,&key)){aoe_cache_count(4);return pc;}
 for(i=0;i<sizeof(key);i++){hash^=((BYTE*)&key)[i];hash*=1099511628211ULL;}if(!hash)hash=1;
 pthread_mutex_lock(&aoe_cache_lock);
 if(!aoe_cache_attempted)aoe_cache_init();aoe_cache_count(0);
 if(!aoe_cache_code)goto done;
 index=hash&(AOE_CACHE_TABLE-1);
 for(i=0;i<64;i++,index=(index+1)&(AOE_CACHE_TABLE-1)){
  struct aoe_cache_entry *e=&aoe_cache_entries[index];
  if(e->hash==hash&&!memcmp(&e->key,&key,sizeof(key))){aoe_cache_count(2);result=(uint64_t)(aoe_cache_code+e->slot*64);break;}
  if(!e->hash){
   BYTE *target;if(aoe_cache_used==AOE_CACHE_COUNT){aoe_cache_count(6);break;}target=aoe_cache_code+aoe_cache_used*64;
   if(!aoe_fragment_emit(&key,(uint64_t)target,emitted)){aoe_cache_count(6);break;}
   memcpy(target,emitted,40);e->key=key;e->slot=aoe_cache_used++;e->hash=hash;aoe_cache_count(3);__atomic_store_n(&aoe_cache_stats[8],aoe_cache_used,__ATOMIC_RELAXED);result=(uint64_t)target;break;
  }
 }
 if(i==64)aoe_cache_count(6);
 if(result!=pc){aoe_cache_thread_original=pc;aoe_cache_thread_shadow=result;aoe_cache_thread_len=key.len;aoe_cache_count(1);}
done:pthread_mutex_unlock(&aoe_cache_lock);return result;
}
